### ISSUE TITLE
NoMethodError when assigning a normalized attribute through a relation on Rails 4.2

### ISSUE THREAD

**Issue by eeng** [dimko/normalizr#2]
Given the following model:
```ruby
class Book < ActiveRecord::Base
  normalize :title
end
```

This will not work (if there is no book with that title):
```
irb(main):002:0> Book.where(title: 'ruby').first_or_initialize.title
  Book Load (0.1ms)  SELECT  "books".* FROM "books" WHERE "books"."title" = ?  ORDER BY "books"."id" ASC LIMIT 1  [["title", "ruby"]]
NoMethodError: super: no superclass method `title=' for #<Book id: nil, title: nil, created_at: nil, updated_at: nil>
	from /Users/Emma/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activemodel-4.2.0/lib/active_model/attribute_methods.rb:430:in `method_missing'
	from /Users/Emma/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/normalizr-0.1.0/lib/normalizr/concern.rb:16:in `block (3 levels) in normalize'
	from /Users/Emma/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/scoping.rb:26:in `block in populate_with_current_scope_attributes'
...
```

But after creating a new object it will:
```
irb(main):001:0> Book.new
=> #<Book id: nil, title: nil, created_at: nil, updated_at: nil>
irb(main):002:0> Book.where(title: 'ruby').first_or_initialize.title
  Book Load (0.2ms)  SELECT  "books".* FROM "books" WHERE "books"."title" = ?  ORDER BY "books"."id" ASC LIMIT 1  [["title", "ruby"]]
=> "ruby"
```

**Comment by atipugin** [comment]
+1

**Comment by dimko** [comment]
@eeng which version of rails are you using? Can't reproduce it on 4.0.13.

**Comment by dimko** [comment]
@eeng okay, got it.

`first_or_initialize` method [silently deprecated and has some bad side effects](https://github.com/rails/rails/issues/9679#issuecomment-16113781).
Using `find_or_initialize_by` instead is fixing this issue.

See also https://github.com/rails/rails/commit/0096f53b25e68c3fc79429253f816fff4a4ee596.
